
services:
  web:
    build: .
    volumes:
      - ./DV_project:/app/DV_project  # 映射程式碼資料夾
      - ./staticfiles:/app/staticfiles  # Django collectstatic 的靜態檔案
    environment:
      - DEBUG=True  # 設定 DEBUG 為 True 以便開發時自動加載程式碼更動
      - ALLOWED_HOSTS=localhost
    expose:
      - "8000"
    command: python manage.py runserver 0.0.0.0:8000  # 使用 Django 自帶的伺服器來運行開發環境
    # 這裡使用 `runserver` 命令，以便開發時自動重新加載修改過的程式碼
    
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:80"
    depends_on:
      - web
